### PR TITLE
add support to virtual repos in xref handler (clone)

### LINKED ISSUE #44: virtualRepos not mapped in xferHandler
It seems like the virtualRepos feature doesn't work for xfer-related operations like clone. The problem seems to be that the xrefHandler doesn't use the resolveRepositoryPath method, which is what encapsulates support for the virtual repos.

### PR DESCRIPTION
**Pull request by mojavelinux**
resolves #44

### CODE REVIEW

**Comment by filmaj** [comment]
Hi @mojavelinux, could you please [sign our CLA](http://opensource.adobe.com/cla.html)?

**Comment by mojavelinux** [comment]
Sure thing. All done!

**Comment by stefan-guggisberg** [comment]
thanks, dan!

**Comment by mojavelinux** [comment]
Thanks for reviewing and merging, @stefan-guggisberg!

Btw, I passed on this project to the isomorphic-git community.

**Pull request merged**
